# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
#- template: folder2/release.yml
- group: 'A variable group'

pool:
  vmImage: ubuntu-latest

steps:
#- script: echo ${{ variables.releaseNo }}

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    method: 'PUT'
    body: |
      "variables": {
          "FromBuild": {
              "isSecret":false, "value": "I DID IT!"
          }
      }
    urlSuffix: 'https://dev.azure.com/iKabbash/_apis/distributedtask/variablegroups/1?api-version=7.0'
    waitForCompletion: 'false'